http:
    # port for app to listen on
    port: 8080
logging:
    console:
        # console log level
        level: info
    file:
        # file log location, remove if only logging to console, also has level
        filename: /var/log/nginx/invalidator.log
cachekill:
    default:
        cache_levels: '1:2'
        cache_dir: /var/spool/nginx
        has_related: false
        redis:
            host: '127.0.0.1'
            port: 6379
    sites:
        my.domain:
            cache_levels: '1:2'
            cache_dir: /var/spool/nginx/my.domain
            has_related: true